name: null
favicon: null
layout_spectrum: 0.17642
typography_spectrum: 0.26387
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#728986'
    - '#171a19'
    - '#333c2e'
    - '#555944'
    - '#c4c8b3'
  brandStrength: 0
  lightness: 0.9375
  saturation: 0.625
  rhythmicContrast: 0
purpose: []
