name: null
favicon: null
layout_spectrum: 0.38953
typography_spectrum: 1
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#b9bbb8'
    - '#a5a7a4'
    - '#6f706b'
    - '#534f46'
    - '#3d3936'
  brandStrength: 0
  lightness: 0.5
  saturation: 0.5
purpose: []
