name: Jeff and Julia
favicon: null
layout_spectrum: 0.1872
typography_spectrum: 0.79709
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#f2efe8'
    - '#c2d4d8'
    - '#b0aac2'
    - '#fefefe'
    - '#cdc4d1'
  brandStrength: 0
  lightness: 0.6875
  saturation: 0.6875
  rhythmicContrast: 0.5
purpose: []
