name: null
favicon: null
layout_spectrum: 0.01107
typography_spectrum: 0.32472
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#728986'
    - '#171a19'
    - '#333c2e'
    - '#555944'
    - '#c4c8b3'
  brandStrength: 0
  lightness: 0.8125
  saturation: 0.4375
  rhythmicContrast: 0.25
purpose: []
