name: null
favicon: null
layout_spectrum: 0.46149
typography_spectrum: 0.13514
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#d9f7f1'
    - '#c8dbd0'
    - '#685840'
    - '#ac9a71'
    - '#b6b597'
  brandStrength: 0
  lightness: 0.5
  saturation: 0.5
purpose: []
