name: Jeff and Julia
favicon: null
layout_spectrum: 0.14822
typography_spectrum: 1
title: The Woods Today
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#3b3a36'
    - '#b3c2bf'
    - '#e9ece5'
    - '#595c58'
    - '#cad4cf'
  brandStrength: 0.25
  lightness: 1
  saturation: 1
  rhythmicContrast: 0.75
purpose: []
