name: null
favicon: null
layout_spectrum: 0.8369
typography_spectrum: 0.69134
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#bcc9d7'
    - '#322c2b'
    - '#8a9dad'
    - '#6e5b5a'
    - '#426da1'
  brandStrength: 0
  lightness: 0.5
  saturation: 0.5
purpose: []
