name: Jeff and Julia
favicon: null
layout_spectrum: 0.2085
typography_spectrum: 1
title: The Woods Today
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#f2efe8'
    - '#c2d4d8'
    - '#b0aac2'
    - '#fefefe'
    - '#cdc4d1'
  brandStrength: 0
  lightness: 1
  saturation: 1
  rhythmicContrast: 0.75
purpose: []
