name: Jeff and Julia
favicon: null
layout_spectrum: 0.22643
typography_spectrum: 1
title: The Woods Today
collections:
  - index:
      path: /
      number: 15
      paginate: true
      navigable: true
    permalink:
      path: '/:title/'
    feed:
      path: /rss.xml
      format: rss
      number: 10
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#949494'
    - '#191418'
    - '#504b4f'
    - '#f3f2f0'
    - '#cccbc9'
  brandStrength: 0
  lightness: 1
  saturation: 1
  rhythmicContrast: 0.25
purpose: []
